language: node_js
node_js:
- '8.9.0'
services:
- postgresql
before_script:
- psql -c 'create database google_translate_server;' -U postgres
addons:
  postgresql: "11"
env:
- PORT=9333 CLIENT_BASE_DOMAIN=http://localhost:5000 DB_NAME=google_translate_server DB_USER=postgres DB_PASS= ENABLE_PSQL=true
